const KEY='room-expense-manager-v2';
const cfg=window.ROOM_EXPENSE_CONFIG||{};
const live=!!(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase);
const sb=live?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{household:{id:crypto.randomUUID(),name:'Our Apartment',email:'',owner:true},roommates:[],expenses:[],audit:[]};
let session={member:null,isAdmin:false};let viewMonth=new Date();viewMonth.setDate(1);let selectedMemberId=null;
const $=id=>document.getElementById(id); const id=()=>crypto.randomUUID();
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function monthKey(d){let x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`;}
function monthLabel(k){let [y,m]=k.split('-');return new Date(+y,+m-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'});}
function currentKey(){return monthKey(viewMonth)}
function money(n){return Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})+' SAR'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(msg,error=false){$('toast').textContent=msg;$('toast').className='toast show '+(error?'error':'');setTimeout(()=>$('toast').className='toast',2600)}
function activeRoommates(){return db.roommates.filter(r=>r.active)}
function monthExpenses(k=currentKey()){return db.expenses.filter(e=>monthKey(e.date)===k)}
function calc(k=currentKey()){
 const rs=activeRoommates(),es=monthExpenses(k),total=es.reduce((s,e)=>s+Number(e.amount),0),spent={};rs.forEach(r=>spent[r.id]=0);es.forEach(e=>spent[e.payerId]=(spent[e.payerId]||0)+Number(e.amount));
 const share=rs.length?total/rs.length:0,balance=rs.map(r=>({id:r.id,name:r.name,spent:spent[r.id]||0,balance:(spent[r.id]||0)-share}));
 let creditors=balance.filter(x=>x.balance>.005).map(x=>({...x,amount:x.balance})),debtors=balance.filter(x=>x.balance<-.005).map(x=>({...x,amount:-x.balance})),settlements=[];
 creditors.forEach(c=>debtors.forEach(d=>{if(c.amount>.005&&d.amount>.005){let a=Math.min(c.amount,d.amount);settlements.push({from:d.name,to:c.name,amount:a});c.amount-=a;d.amount-=a}}));return{rs,es,total,spent,balance,share,settlements};
}
async function hashPassword(p){const data=new TextEncoder().encode(p),salt=new TextEncoder().encode('room-expense-v2-static-salt');const key=await crypto.subtle.importKey('raw',data,'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);return [...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function log(action,type,recordId,details){db.audit.unshift({id:id(),action,type,recordId,details,user:session.member?.name||'System',at:new Date().toISOString()});save();}
async function persist(){save();if(!live)return;try{await syncToSupabase()}catch(e){console.error(e);toast('Saved locally; cloud sync failed',true)}}
async function syncToSupabase(){const h=db.household;if(!h?.id)return;await sb.from('households').upsert({id:h.id,name:h.name,email:h.email,owner_user_id:h.owner_user_id});await sb.from('members').upsert(db.roommates.map(r=>({id:r.id,household_id:h.id,name:r.name,active:r.active,password_hash:r.passwordHash,is_admin:!!r.isAdmin})));await sb.from('expenses').upsert(db.expenses.map(e=>({id:e.id,household_id:h.id,description:e.description,amount:e.amount,payer_member_id:e.payerId,expense_date:e.date,category:e.category||null,notes:e.notes||null,created_by_member_id:e.createdBy||null,updated_at:e.updatedAt||new Date().toISOString()})));if(db.audit.length)await sb.from('audit_log').upsert(db.audit.map(a=>({id:a.id,household_id:h.id,actor_member_id:session.member?.id||null,action:a.action,entity_type:a.type,entity_id:a.recordId,details:{text:a.details,user:a.user},created_at:a.at})));}
async function loadCloud(){if(!live)return;const h=db.household;const {data:hs,error:he}=await sb.from('households').select('*').eq('owner_user_id',(await sb.auth.getUser()).data.user.id).limit(1);if(he)throw he;if(hs?.[0]){db.household={id:hs[0].id,name:hs[0].name,email:hs[0].email,owner_user_id:hs[0].owner_user_id};const hid=hs[0].id;const [m,e,a]=await Promise.all([sb.from('members').select('*').eq('household_id',hid),sb.from('expenses').select('*').eq('household_id',hid),sb.from('audit_log').select('*').eq('household_id',hid).order('created_at',{ascending:false})]);db.roommates=(m.data||[]).map(x=>({id:x.id,name:x.name,active:x.active,passwordHash:x.password_hash,isAdmin:x.is_admin}));db.expenses=(e.data||[]).map(x=>({id:x.id,description:x.description,amount:Number(x.amount),payerId:x.payer_member_id,date:x.expense_date,category:x.category||'',notes:x.notes||'',createdBy:x.created_by_member_id,updatedAt:x.updated_at}));db.audit=(a.data||[]).map(x=>({id:x.id,action:x.action,type:x.entity_type,recordId:x.entity_id,details:x.details?.text||'',user:x.details?.user||'System',at:x.created_at}));save();}}
function show(el,on=true){el.classList.toggle('hidden',!on)}
function resetMemberScreen(){selectedMemberId=null;$('memberPassword').value='';show($('memberPasswordBox'),false);$('memberChoices').innerHTML=db.roommates.filter(r=>r.active).map(r=>`<button class="member-choice" data-member="${r.id}"><span>${esc(r.name)}</span><small>${r.isAdmin?'Household admin':'Roommate'}</small></button>`).join('')||'<p class="muted">No roommates have been added yet. The first profile will be created automatically.</p>';document.querySelectorAll('.member-choice').forEach(b=>b.onclick=()=>{selectedMemberId=b.dataset.member;$('memberPasswordLabel').firstChild.textContent=`${db.roommates.find(r=>r.id===selectedMemberId).name} password`;show($('memberPasswordBox'));$('memberPassword').focus()})}
async function enterMember(){const r=db.roommates.find(x=>x.id===selectedMemberId),p=$('memberPassword').value;if(!r||!p)return toast('Choose a profile and enter its password',true);if((await hashPassword(p))!==r.passwordHash)return toast('Incorrect profile password',true);session.member=r;session.isAdmin=!!r.isAdmin;show($('memberScreen'),false);show($('appShell'));$('profileBadge').textContent=`${r.name}${session.isAdmin?' · Admin':''}`;$('householdSubtitle').textContent=`${db.household.name} · Live shared household`;applyPermissions();render();toast(`Welcome, ${r.name}`)}
function applyPermissions(){show($('adminRoommateTools'),session.isAdmin);document.querySelectorAll('.admin-only').forEach(x=>show(x,session.isAdmin))}
function render(){renderDashboard();renderExpenses();renderRoommates();renderHistory();renderAudit();$('syncStatus').innerHTML=live?'🟢 Connected to shared cloud database.':'🟠 Local demo mode — add Supabase settings in <b>config.js</b> for shared multi-device data.'}
function renderDashboard(){const k=currentKey(),c=calc(k);$('monthTitle').textContent=monthLabel(k);$('expenseMonthTitle').textContent=monthLabel(k);$('summaryCards').innerHTML=[['Total spent',money(c.total)],['Equal share',money(c.share)],['Expenses',c.es.length],['Roommates',c.rs.length]].map(x=>`<div class="card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('spendingTable').innerHTML=c.rs.length?`<table><tr><th>Roommate</th><th>Spent</th><th>Share</th><th>Difference</th></tr>${c.balance.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.spent)}</td><td>${money(c.share)}</td><td class="${x.balance>=0?'positive':'negative'}">${x.balance>=0?'+':''}${money(x.balance)}</td></tr>`).join('')}</table>`:'<div class="empty">Add roommates first.</div>';$('settlementTable').innerHTML=c.settlements.length?`<table><tr><th>Who pays</th><th>Who receives</th><th>Amount</th></tr>${c.settlements.map(x=>`<tr><td>${esc(x.from)}</td><td>${esc(x.to)}</td><td>${money(x.amount)}</td></tr>`).join('')}</table>`:'<div class="empty">Everyone is settled.</div>';$('monthlyDetails').innerHTML=`<p><b>${monthLabel(k)}</b></p><p>Most spent: <b>${esc(c.balance.slice().sort((a,b)=>b.spent-a.spent)[0]?.name||'—')}</b> · Highest single expense: <b>${money(Math.max(0,...c.es.map(e=>Number(e.amount))))}</b></p>`}
function renderExpenses(){const es=monthExpenses();const mine=es.filter(e=>e.payerId===session.member?.id);$('expenseList').innerHTML=mine.length?`<table><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th><th></th></tr>${mine.sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<tr><td>${e.date}</td><td>${esc(e.description)}</td><td><span class="tag">${esc(e.category||'Other')}</span></td><td>${money(e.amount)}</td><td class="row-actions"><button onclick="editExpense('${e.id}')">Correct</button></td></tr>`).join('')}</table>`:'<div class="empty">You have no expenses this month.</div>'}
function renderRoommates(){$('roommateList').innerHTML=db.roommates.map(r=>`<div class="roommate-row"><div><b>${esc(r.name)}</b> ${r.active?'':'<span class="tag">inactive</span>'}<small>${r.isAdmin?'Admin profile':'Roommate profile'}</small></div>${session.isAdmin?`<div class="row-actions"><button onclick="renameRoommate('${r.id}')">Rename</button><button onclick="resetRoommatePassword('${r.id}')">Reset password</button><button onclick="toggleRoommate('${r.id}')">${r.active?'Deactivate':'Activate'}</button></div>`:''}</div>`).join('')}
function renderHistory(){let keys=[...new Set(db.expenses.map(e=>monthKey(e.date)))].sort().reverse();if(!keys.includes(currentKey()))keys.unshift(currentKey());$('historyList').innerHTML=keys.map(k=>{let c=calc(k);return `<div class="card history-card"><b>${monthLabel(k)}</b><p>Total ${money(c.total)} · ${c.es.length} expenses · Equal share ${money(c.share)}</p><p>${c.balance.map(x=>`${esc(x.name)}: ${money(x.spent)}`).join(' · ')}</p><button onclick="jumpMonth('${k}')">Open month</button></div>`}).join('')}
function renderAudit(){$('auditList').innerHTML=db.audit.length?`<table><tr><th>Time</th><th>User</th><th>Action</th><th>Details</th></tr>${db.audit.map(a=>`<tr><td>${new Date(a.at).toLocaleString()}</td><td>${esc(a.user)}</td><td>${esc(a.action)}</td><td>${esc(a.details)}</td></tr>`).join('')}</table>`:'<div class="empty">No changes recorded.</div>'}
async function createHousehold(){const email=$('signupEmail').value.trim(),pw=$('signupPassword').value,hn=$('signupHousehold').value.trim()||'Our Apartment';if(!email||pw.length<8)return toast('Use a valid email and an 8+ character shared password',true);if(live){const {data,error}=await sb.auth.signUp({email,password:pw});if(error)return toast(error.message,true);if(!data.user)return toast('Check your email to confirm the account',true);db.household={id:id(),name:hn,email,owner_user_id:data.user.id};}else db.household={id:id(),name:hn,email,owner:true};const hp=await hashPassword(pw);const r={id:id(),name:'Roommate 01',active:true,passwordHash:hp,isAdmin:true};db.roommates=[r];db.expenses=[];db.audit=[];session.member=null;save();if(live)await persist();toast('Household created. Add the other roommates.');show($('authScreen'),false);resetMemberScreen();show($('memberScreen'));}
async function login(){const email=$('loginEmail').value.trim(),pw=$('loginPassword').value;if(!email||!pw)return toast('Enter email and password',true);if(live){const {error}=await sb.auth.signInWithPassword({email,password:pw});if(error)return toast(error.message,true);const {data:userData}=await sb.auth.getUser();const {data:hs,error:he}=await sb.from('households').select('*').eq('owner_user_id',userData.user.id).limit(1);if(he||!hs?.[0])return toast('No household found for this account',true);db.household={id:hs[0].id,name:hs[0].name,email:hs[0].email,owner_user_id:hs[0].owner_user_id};await loadCloud();}else{if(db.household.email&&email!==db.household.email)return toast('Email does not match this household',true);if(db.roommates[0]?.passwordHash&&(await hashPassword(pw))!==db.roommates[0].passwordHash)return toast('Incorrect shared password',true);db.household.email=email;}save();show($('authScreen'),false);resetMemberScreen();show($('memberScreen'));}
async function logout(){if(live)await sb.auth.signOut();session={member:null,isAdmin:false};show($('appShell'),false);show($('memberScreen'),false);show($('authScreen'));}
$('showSignup').onclick=()=>{show($('authModeLogin'),false);show($('authModeSignup'))};$('showLogin').onclick=()=>{show($('authModeSignup'),false);show($('authModeLogin'))};$('loginBtn').onclick=login;$('signupBtn').onclick=createHousehold;$('enterProfile').onclick=enterMember;$('backMembers').onclick=resetMemberScreen;$('logoutFromMember').onclick=logout;$('switchProfile').onclick=()=>{show($('appShell'),false);resetMemberScreen();show($('memberScreen'))};$('logoutBtn').onclick=logout;
$('expenseForm').onsubmit=async e=>{e.preventDefault();const eid=$('expenseId').value,amt=Number($('amount').value);if(!amt||amt<=0)return toast('Enter a positive amount',true);if(!session.member)return;let obj={id:eid||id(),description:$('description').value.trim()||'Expense',amount:amt,payerId:session.member.id,date:$('expenseDate').value,category:$('category').value.trim(),notes:$('notes').value.trim(),createdBy:session.member.id,updatedAt:new Date().toISOString()};if(eid){let old=db.expenses.find(x=>x.id===eid);if(!old||old.payerId!==session.member.id)return toast('You can only correct your own expense',true);db.expenses=db.expenses.map(x=>x.id===eid?{...x,...obj}:x);log('Corrected expense','expense',eid,`${money(old.amount)} → ${money(obj.amount)} · ${obj.description}`)}else{db.expenses.push(obj);log('Added expense','expense',obj.id,`Added ${obj.description} (${money(obj.amount)})`)}await persist();resetExpense();render();toast('Expense saved')};
function resetExpense(){$('expenseForm').reset();$('expenseId').value='';$('expenseDate').value=new Date().toISOString().slice(0,10)}$('cancelEdit').onclick=resetExpense;
window.editExpense=eid=>{let e=db.expenses.find(x=>x.id===eid);if(!e||e.payerId!==session.member.id)return;Object.assign($('expenseId'),{value:e.id});$('description').value=e.description;$('amount').value=e.amount;$('expenseDate').value=e.date;$('category').value=e.category;$('notes').value=e.notes;document.querySelector('[data-tab="expenses"]').click()};
$('roommateForm').onsubmit=async e=>{e.preventDefault();if(!session.isAdmin)return;const name=$('roommateName').value.trim(),pw=$('roommatePassword').value;if(!name||pw.length<4)return toast('Name and a 4+ character profile password are required',true);const r={id:id(),name,active:true,passwordHash:await hashPassword(pw),isAdmin:false};db.roommates.push(r);log('Added roommate','roommate',r.id,`Added ${name}`);await persist();$('roommateForm').reset();render();toast(`${name} added`)};
window.renameRoommate=async rid=>{if(!session.isAdmin)return;let r=db.roommates.find(x=>x.id===rid),n=prompt('New roommate name',r?.name);if(n?.trim()){let old=r.name;r.name=n.trim();log('Renamed roommate','roommate',rid,`${old} → ${r.name}`);await persist();render()}};
window.resetRoommatePassword=async rid=>{if(!session.isAdmin)return;let r=db.roommates.find(x=>x.id===rid),p=prompt(`New password for ${r.name}`);if(p&&p.length>=4){r.passwordHash=await hashPassword(p);log('Reset roommate password','roommate',rid,`Password reset for ${r.name}`);await persist();toast('Password reset')}};
window.toggleRoommate=async rid=>{if(!session.isAdmin)return;let r=db.roommates.find(x=>x.id===rid);if(!r)return;if(r.id===session.member.id&&r.active)return toast('You cannot deactivate your current profile',true);r.active=!r.active;log(r.active?'Activated roommate':'Deactivated roommate','roommate',rid,`${r.name} is now ${r.active?'active':'inactive'}`);await persist();render()};
window.jumpMonth=k=>{let[y,m]=k.split('-');viewMonth=new Date(+y,+m-1,1);render();document.querySelector('[data-tab="dashboard"]').click()};$('prevMonth').onclick=()=>{viewMonth.setMonth(viewMonth.getMonth()-1);render()};$('nextMonth').onclick=()=>{viewMonth.setMonth(viewMonth.getMonth()+1);render()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
$('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='room-expenses-backup.json';a.click()};$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{const x=JSON.parse(rd.result);if(!x.roommates||!x.expenses)throw Error();if(live&&!session.isAdmin)return toast('Only admin can import data',true);db=x;save();if(live)await persist();render();toast('Backup imported')}catch{toast('Invalid backup file',true)}};rd.readAsText(f)};$('resetBtn').onclick=()=>{if(session.isAdmin&&confirm('Delete all local data?')){localStorage.removeItem(KEY);location.reload()}};
(async()=>{if(live){try{const {data}=await sb.auth.getSession();if(data.session){await loadCloud();show($('authScreen'),false);resetMemberScreen();show($('memberScreen'))}}catch(e){console.error(e);}}else if(db.household?.email&&db.roommates.length){$('loginEmail').value=db.household.email}show($('configNotice'),!live);if(!live)$('configNotice').textContent='Demo mode is active. For real shared login and multi-device sync, add your Supabase URL and anon key to config.js, then run the SQL in backend-schema.sql.'})();
